# Project Name
TARGET = DattorroReverb

# Sources
CPP_SOURCES = DattorroReverb.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

APP_TYPE = BOOT_SRAM
# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
